services:

  mcp-server:
    build:
      context: ./agent

    command: python mcp_server.py

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - hf-cache:/root/.cache/huggingface

    restart: unless-stopped


  telegram-bot:
    build:
      context: ./agent

    command: python telegram_bot.py

    env_file:
      - .env

    environment:
      MCP_SERVER_URL: http://mcp-server:8000/mcp

    depends_on:
      - mcp-server

    volumes:
      - hf-cache:/root/.cache/huggingface

    restart: unless-stopped


volumes:
  hf-cache: